#!/bin/sh

# Kill previous processes

killall -q sxhkd
killall -q polybar 
killall -q picom 
killall -q redshift
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Set up audio & window compositor

start-pulseaudio-x11
picom -f -D 0 --xrender-sync --xrender-sync-fence &

# Monitor configuation

xsetroot -cursor_name left_ptr
large_monitor_line=$(xrandr --query | grep -e '^DP1')
if [[ $large_monitor_line = *disconnected* ]]; then
    xrandr --output eDP1 --primary --mode 3000x2000 --rotate normal
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
    polybar top_edp1 & 
else
    xrandr --output eDP1 --primary --mode 3000x2000 --rotate normal --output DP1 --mode 3840x2160 --rotate normal --left-of eDP1
    bspc monitor DP1 -d 1 2 3 4 5
    bspc monitor eDP1 -d 6 7 8 9 0
    polybar top_edp1 & 
    polybar top_dp1 &
fi
feh --bg-fill ~/.dotfiles/wallpapers/white_sand.jpg &
# redshift -l 34.052235:-118.243683 -t 6500:4000 &
redshift -l 39.952583:-75.165222 -t 6500:4000 &

# BSPC configuation

bspc config border_width         3
bspc config window_gap          25

bspc config focused_border_color \#e3e8e3

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -r "*"
bspc rule -a Zathura state=tiled

# Allow user to press hotkeys

sxhkd &
