#!/bin/sh

start-pulseaudio-x11
compton -f -D 6 --xrender-sync --xrender-sync-fence &
sh ~/.config/polybar/launch.sh
xrandr --output DP1 --scale 1.5626x1.5626 --same-as eDP1
feh --bg-fill ~/.dotfiles/wallpapers/akira.jpg &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap          22

bspc config focused_border_color \#e3e8e3

bspc config split_ratio          0.57
bspc config borderless_monocle   true
bspc config gapless_monocle      true
