#!/bin/sh

# Old process removal

killall -q sxhkd
killall -q polybar 
killall -q picom 
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Spawn new processes

sxhkd &
start-pulseaudio-x11
picom -f -D 0 --xrender-sync --xrender-sync-fence &
polybar main &
feh --bg-fill ~/.dotfiles/wallpapers/akira.jpg &

# X configuration

xrandr --output DP1 --scale 1.5626x1.5626 --same-as eDP1
xsetroot -cursor_name left_ptr

# BSPC configuation

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap          22

bspc config focused_border_color \#e3e8e3

bspc config split_ratio          0.57
bspc config borderless_monocle   true
bspc config gapless_monocle      true
